import { NewsArticle, TickerItem } from "./types";

// ── Mock Data for Demo & Development ─────────────────────────

export const MOCK_TICKER: TickerItem[] = [
  { id: "t1", title: "🔴 URGENTE: OpenAI lanza GPT-5 con capacidades de razonamiento avanzado", category: "tech", isLive: true },
  { id: "t2", title: "📊 Bitcoin supera los $150.000 USD por primera vez en la historia", category: "business", isLive: false },
  { id: "t3", title: "🇨🇱 Chile lidera ranking de adopción IA en Latinoamérica según MIT", category: "chile", isLive: false },
  { id: "t4", title: "🚀 SpaceX Starship completa primer vuelo orbital comercial exitoso", category: "tech", isLive: true },
  { id: "t5", title: "💼 Evento LIVE: Conferencia de prensa Casa Blanca sobre regulación IA", category: "live", isLive: true },
  { id: "t6", title: "🤖 Google DeepMind presenta Gemini Ultra 2.0 con benchmark récord", category: "tech", isLive: false },
  { id: "t7", title: "📱 Apple revela Vision Pro 2 con IA generativa integrada", category: "tech", isLive: false },
  { id: "t8", title: "🌎 Cumbre G20: acuerdan marco regulatorio global para IA", category: "world", isLive: false },
];

export const MOCK_ARTICLES: NewsArticle[] = [
  {
    id: "1",
    group_id: "g1",
    title: "OpenAI lanza GPT-5: El modelo de IA más potente del mundo con razonamiento autónomo",
    summary: "La nueva generación de inteligencia artificial de OpenAI promete revolucionar la forma en que interactuamos con la tecnología, con capacidades de razonamiento multimodal sin precedentes.",
    content: "",
    enriched_content: "OpenAI ha presentado oficialmente GPT-5, marcando un hito sin precedentes en la historia de la inteligencia artificial. El nuevo modelo demuestra capacidades de razonamiento autónomo que superan significativamente a su predecesor, logrando resultados sobresalientes en benchmarks de matemáticas, programación y análisis científico.\n\nSam Altman, CEO de OpenAI, declaró durante la presentación en San Francisco que GPT-5 representa 'el salto más grande que hemos dado como empresa'. El modelo incorpora lo que la compañía denomina 'razonamiento en cadena profunda', permitiéndole descomponer problemas complejos en pasos lógicos de manera autónoma.\n\nEntre las mejoras más destacadas se encuentran: procesamiento multimodal nativo (texto, imagen, audio y video simultáneamente), una ventana de contexto de 1 millón de tokens, y la capacidad de ejecutar código en tiempo real para verificar sus propias respuestas.\n\nLa comunidad tecnológica ha reaccionado con entusiasmo cauteloso. Investigadores de Stanford y MIT han confirmado que los primeros benchmarks independientes muestran mejoras del 40% en tareas de razonamiento complejo respecto a GPT-4o. Sin embargo, expertos en ética de IA señalan la necesidad de evaluar cuidadosamente los riesgos asociados a modelos cada vez más autónomos.",
    sources: [{ name: "OpenAI Blog", url: "https://openai.com/blog/gpt-5" }],
    ai_model: "grok-4.1-fast",
    image_url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
    category: "tech",
    tags: ["IA", "OpenAI", "GPT-5", "Tecnología"],
    author: "Equipo NewsBI",
    published_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    slug: 'openai-lanza-gpt5',
    is_live: true,
    live_youtube_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    audio_url: null,
    sentiment: "positive",
    relevance_score: 0.98,
    embedding: null,
  },
  {
    id: "2",
    group_id: "g2",
    title: "Bitcoin rompe la barrera de los $150.000: ¿Qué significa para el mercado global?",
    summary: "La criptomoneda líder alcanza un nuevo máximo histórico impulsada por la adopción institucional masiva y los ETFs de Bitcoin.",
    content: "",
    enriched_content: "Bitcoin ha superado oficialmente la marca de los $150.000 USD, estableciendo un nuevo récord histórico que ha generado ondas expansivas en los mercados financieros globales. El rally, que comenzó a principios de mes, se ha acelerado tras el anuncio de grandes fondos de inversión que aumentaron significativamente sus posiciones en ETFs de Bitcoin.\n\nLarry Fink, CEO de BlackRock, calificó a Bitcoin como 'el activo de la década' durante una entrevista en Bloomberg, señalando que el iShares Bitcoin Trust (IBIT) ha superado los $100 mil millones en activos bajo gestión.\n\nAnalistas de Goldman Sachs y JP Morgan han revisado al alza sus proyecciones, con algunos estimando que Bitcoin podría alcanzar los $200.000 antes de fin de año. Sin embargo, advierten sobre la volatilidad inherente del mercado cripto.\n\nEn Chile, el interés por las criptomonedas ha crecido un 300% según datos de plataformas locales como Buda.com, con miles de nuevos usuarios registrándose semanalmente.",
    sources: [{ name: "Bloomberg", url: "https://bloomberg.com/crypto/bitcoin-150k" }],
    ai_model: "grok-4.1-fast",
    image_url: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=800&q=80",
    category: "business",
    tags: ["Bitcoin", "Criptomonedas", "Finanzas", "ETF"],
    author: "Equipo NewsBI",
    published_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    slug: 'bitcoin-rompe-barrera-150k',
    is_live: false,
    live_youtube_url: null,
    audio_url: null,
    sentiment: "positive",
    relevance_score: 0.95,
    embedding: null,
  },
  {
    id: "3",
    group_id: "g3",
    title: "Chile lidera la adopción de Inteligencia Artificial en Latinoamérica",
    summary: "Un estudio del MIT Technology Review posiciona a Chile como el país más avanzado de la región en implementación de IA en sector público y privado.",
    content: "",
    enriched_content: "Chile se ha posicionado como el líder indiscutido en adopción de inteligencia artificial en América Latina, según el último informe del MIT Technology Review publicado esta semana. El estudio evalúa factores como infraestructura digital, políticas públicas, inversión en I+D y talento tecnológico.\n\nEl país destaca particularmente por su Política Nacional de IA, considerada la más completa de la región, y por iniciativas como el Centro Nacional de Inteligencia Artificial (CENIA), que ha producido investigaciones citadas internacionalmente.\n\nEmpresas chilenas como NotCo, Fintual y Betterfly han sido reconocidas como casos de éxito en la aplicación de IA a negocios escalables. Además, el ecosistema de startups de IA en Santiago ha crecido un 250% en los últimos dos años.\n\nEl Ministro de Ciencia y Tecnología destacó que Chile invertirá $500 millones de dólares adicionales en infraestructura de IA durante los próximos tres años, incluyendo la construcción de un centro de datos soberano y programas de capacitación masiva.",
    sources: [{ name: "MIT Technology Review", url: "https://technologyreview.com/chile-ai-latam" }],
    ai_model: "grok-4.1-fast",
    image_url: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&q=80",
    category: "chile",
    tags: ["Chile", "IA", "Tecnología", "Latinoamérica"],
    author: "Equipo NewsBI",
    published_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    slug: 'chile-lidera-adopcion-ia',
    is_live: false,
    live_youtube_url: null,
    audio_url: null,
    sentiment: "positive",
    relevance_score: 0.92,
    embedding: null,
  },
  {
    id: "4",
    group_id: "g4",
    title: "Conferencia de prensa Casa Blanca: Nueva regulación para IA y tecnología",
    summary: "El presidente anuncia un marco regulatorio histórico para la inteligencia artificial, con implicaciones globales para la industria tech.",
    content: "",
    enriched_content: "La Casa Blanca ha anunciado un marco regulatorio integral para la inteligencia artificial que marca un antes y después en la relación entre gobierno y tecnología. La conferencia de prensa, que se transmite en vivo, detalla las nuevas políticas que afectarán a todas las empresas de IA operando en Estados Unidos.\n\nEntre los puntos clave se encuentran: requisitos obligatorios de transparencia para modelos de IA con más de 100 mil millones de parámetros, evaluaciones de seguridad independientes antes del despliegue comercial, y la creación de una agencia federal dedicada exclusivamente a la supervisión de IA.\n\nLas grandes tecnológicas han mostrado reacciones mixtas. Microsoft y Google han expresado apoyo cauteloso, mientras que startups más pequeñas advierten que la regulación podría frenar la innovación. OpenAI y Anthropic han sido los más vocales en apoyar el nuevo marco.\n\nLa regulación entraría en vigor en 90 días y se espera que influencie significativamente las políticas de IA en Europa y Asia.",
    sources: [{ name: "White House Press", url: "https://whitehouse.gov/ai-regulation" }],
    ai_model: "grok-4.1-fast",
    image_url: "https://images.unsplash.com/photo-1501466044931-62695aada8e9?w=800&q=80",
    category: "tech",
    tags: ["Casa Blanca", "Regulación IA", "Política", "Tecnología"],
    author: "Equipo NewsBI",
    published_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    slug: 'conferencia-casa-blanca-ia',
    is_live: true,
    live_youtube_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    audio_url: null,
    sentiment: "neutral",
    relevance_score: 0.97,
    embedding: null,
  },
  {
    id: "5",
    group_id: "g5",
    title: "Google DeepMind presenta Gemini Ultra 2.0: nuevo estándar en IA multimodal",
    summary: "El modelo más avanzado de Google promete superar a GPT-5 en tareas de visión y razonamiento científico.",
    content: "",
    enriched_content: "Google DeepMind ha revelado Gemini Ultra 2.0, su modelo de inteligencia artificial más ambicioso hasta la fecha. Presentado en un evento especial en Mountain View, el nuevo modelo establece récords en 15 de los 20 benchmarks más importantes de la industria.\n\nDemis Hassabis, CEO de DeepMind, describió a Gemini Ultra 2.0 como 'el modelo más capaz que la humanidad ha creado'. Entre sus características más impresionantes se encuentra la capacidad de analizar videos de hasta 2 horas de duración, generar código ejecutable en más de 50 lenguajes de programación, y realizar investigación científica autónoma.\n\nEl modelo será integrado en toda la suite de productos de Google, incluyendo Search, Workspace, Cloud y Android. Google también anunció una versión especial para desarrolladores con acceso a través de Vertex AI.\n\nLa competencia con OpenAI se intensifica, con ambas empresas lanzando actualizaciones cada vez más frecuentes en una carrera que está acelerando el progreso de la IA a un ritmo sin precedentes.",
    sources: [{ name: "Google Blog", url: "https://blog.google/gemini-ultra-2" }],
    ai_model: "grok-4.1-fast",
    image_url: "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&q=80",
    category: "tech",
    tags: ["Google", "DeepMind", "Gemini", "IA"],
    author: "Equipo NewsBI",
    published_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    slug: 'google-presenta-gemini-ultra',
    is_live: false,
    live_youtube_url: null,
    audio_url: null,
    sentiment: "positive",
    relevance_score: 0.93,
    embedding: null,
  },
  {
    id: "6",
    group_id: "g6",
    title: "Startup chilena Fintual alcanza los $5.000 millones USD en activos administrados",
    summary: "La fintech chilena continúa su expansión en Latinoamérica, consolidándose como uno de los unicornios más exitosos de la región.",
    content: "",
    enriched_content: "Fintual, la startup fintech nacida en Chile, ha alcanzado un hito histórico al superar los $5.000 millones de dólares en activos bajo administración. Este logro posiciona a la empresa como una de las gestoras de inversiones digitales más grandes de América Latina.\n\nFundada en 2018 por un grupo de ingenieros chilenos, Fintual ha revolucionado la forma en que los latinoamericanos invierten, democratizando el acceso a instrumentos financieros sofisticados a través de una plataforma simple y transparente.\n\nLa empresa, que opera en Chile, México y Colombia, anunció además una nueva ronda de inversión de $200 millones liderada por Sequoia Capital, valorando la compañía en $2.5 mil millones.\n\nEl CEO de Fintual atribuyó el éxito a la combinación de tecnología de punta, incluyendo modelos de IA para optimización de portafolios, con un enfoque obsesivo en la experiencia del usuario y la educación financiera.",
    sources: [{ name: "TechCrunch", url: "https://techcrunch.com/fintual-5b" }],
    ai_model: "grok-4.1-fast",
    image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    category: "business",
    tags: ["Fintual", "Chile", "Fintech", "Inversiones"],
    author: "Equipo NewsBI",
    published_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    slug: 'startup-fintual-5000m',
    is_live: false,
    live_youtube_url: null,
    audio_url: null,
    sentiment: "positive",
    relevance_score: 0.88,
    embedding: null,
  },
];

export function getMockArticleById(id: string): NewsArticle | undefined {
  return MOCK_ARTICLES.find((a) => a.id === id);
}

export function getMockArticlesByCategory(category: string): NewsArticle[] {
  if (category === "all" || category === "inicio") return MOCK_ARTICLES;
  if (category === "live") return MOCK_ARTICLES.filter((a) => a.is_live);
  if (category === "audio") return MOCK_ARTICLES.filter((a) => a.audio_url);
  return MOCK_ARTICLES.filter((a) => a.category === category);
}
